// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKkgi-xAhZlmJ_JRxpmyzC1NEZoFBue8Y',
    appId: '1:721732501125:web:dabb5d7823dade6f6bf3ec',
    messagingSenderId: '721732501125',
    projectId: 'clothingapp224',
    authDomain: 'clothingapp224.firebaseapp.com',
    storageBucket: 'clothingapp224.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_QyvUgm1CkRdIXJymZ_w2ceOauFENGw',
    appId: '1:721732501125:android:3e196d1436ea16536bf3ec',
    messagingSenderId: '721732501125',
    projectId: 'clothingapp224',
    storageBucket: 'clothingapp224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkAP4v7-bmr_meWcN-x0psNtMzmSsdA8A',
    appId: '1:721732501125:ios:9b01bf443141a9f06bf3ec',
    messagingSenderId: '721732501125',
    projectId: 'clothingapp224',
    storageBucket: 'clothingapp224.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkAP4v7-bmr_meWcN-x0psNtMzmSsdA8A',
    appId: '1:721732501125:ios:9b01bf443141a9f06bf3ec',
    messagingSenderId: '721732501125',
    projectId: 'clothingapp224',
    storageBucket: 'clothingapp224.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKkgi-xAhZlmJ_JRxpmyzC1NEZoFBue8Y',
    appId: '1:721732501125:web:0ba9fceb795dcfda6bf3ec',
    messagingSenderId: '721732501125',
    projectId: 'clothingapp224',
    authDomain: 'clothingapp224.firebaseapp.com',
    storageBucket: 'clothingapp224.firebasestorage.app',
  );
}
